# ---------------- #
#   Main Configs   #
# ---------------- #
#baseurl:
#url: https://mazhuang.org
date_format: "ordinal"
title: khz
#subtitle: "k-hengzhou"
description: "Mathematics explains everything"
keywords: khz, slam, imu, gnss, vo vslam
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2023
# 源码仓库，请替换成自己的
repository: k-hengzhou/k-hengzhou.github.io
# 对 css 和 js 资源的 cdn 加速配置

author: wang hengzhou
organization: 
organization_url: 
github_username: k-hengzhou
location: xiamen, China
email: whang1617116@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /wiki/
    label: 代码

  -
    href: /about/
    label: 关于

markdown: kramdown
kramdown:
    input: GFM
    math_engine: null
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-seo-tag
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

